import type { PhotoCollection } from './types';
import galleryManifest from './gallery-manifest.json';

/**
 * Photo paths are relative to public/. Gallery subcategories (B&W / Color)
 * are driven by gallery-manifest.json, generated by: npm run classify-photos
 */

const base = (import.meta as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
const stillLifeBase = (base.endsWith('/') ? base.slice(0, -1) : base) + '/photos/still-life';
const SUPPORTED_IMAGE_FILE = /\.(jpe?g|png|webp)$/i;

function photosFromFilenames(filenames: string[], subdir: 'bw' | 'color' | 'redscale', prefix: string) {
  return filenames.map((filename, i) => {
    const slug = filename.replace(/\.[^.]+$/, '').replace(/[^a-z0-9_-]/gi, '_');
    return {
      id: `${prefix}-${i + 1}`,
      src: `${stillLifeBase}/${subdir}/${filename}`,
      alt: `Still life ${slug}`,
      caption: '',
    };
  });
}

function selectGalleryFilenames(filenames: string[]): string[] {
  return filenames.filter((filename) => SUPPORTED_IMAGE_FILE.test(filename));
}

type GalleryManifest = {
  bw?: string[];
  color?: string[];
  redscale?: string[];
  'still-life'?: string[];
};

const manifest = galleryManifest as GalleryManifest;
const bwPhotos = photosFromFilenames(selectGalleryFilenames(manifest.bw ?? []), 'bw', 'bw');
const colorPhotos = photosFromFilenames(selectGalleryFilenames(manifest.color ?? []), 'color', 'color');
const redscalePhotos = photosFromFilenames(selectGalleryFilenames(manifest.redscale ?? []), 'redscale', 'redscale');

function resolveAboutImagePath(entry: string): string {
  const normalized = entry.trim().replace(/^\/+/, '');
  if (!normalized) return '';
  if (normalized.startsWith('bw/') || normalized.startsWith('color/')) {
    return `${stillLifeBase}/${normalized}`;
  }
  return `${stillLifeBase}/${normalized}`;
}

const aboutFilename = (manifest['still-life'] ?? []).find((filename) => SUPPORTED_IMAGE_FILE.test(filename));
export const ABOUT_IMAGE_SRC = aboutFilename
  ? resolveAboutImagePath(aboutFilename)
  : `${stillLifeBase}/about_me.jpg`;

export const COLLECTIONS: PhotoCollection[] = [
  { id: 'still-life-bw', title: 'Black & White', photos: bwPhotos },
  { id: 'still-life-color', title: 'Color', photos: colorPhotos },
  { id: 'still-life-redscale', title: 'Redscale', photos: redscalePhotos },
];

export const ABOUT = {
  name: 'adubsqz',
  tagline: 'Photography',
  contactEmail: 'alexanderthomasames@gmail.com',
  bio: 'Originally from the Southwest, Alexander moved to New York several years ago and rediscovered his love for film photography. He first learned the craft in high school, spending long hours in the darkroom developing film and printing on Ilford paper—a passion that stayed dormant until recently. By trade, Alexander works as a data scientist and software engineer at a biomolecular research company focused on fighting cancer.',
  socials: [
    { name: 'Instagram', url: 'https://www.instagram.com/adubsqz/' },
    { name: 'GitHub', url: 'https://github.com' },
  ],
};
